-- ============================================================================
-- BEGIN AGAIN COFFEE - MASTER SCHEMA INIT
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CUSTOM TYPES (ENUMS)
-- ----------------------------------------------------------------------------
CREATE TYPE public.ledger_state AS ENUM ('active', 'voided', 'refunded');
CREATE TYPE public.fulfillment_state AS ENUM ('preparing', 'served', 'cancelled');
CREATE TYPE public.order_kind AS ENUM ('sale', 'refund');
CREATE TYPE public.payment_type AS ENUM ('cash', 'qris', 'comped');
CREATE TYPE public.shift_type AS ENUM ('day', 'night');
CREATE TYPE public.profile_role AS ENUM ('manager', 'barista');
CREATE TYPE public.modifier_type AS ENUM ('bean', 'syrup', 'milk', 'packaging');
CREATE TYPE public.modifier_behavior AS ENUM ('STATIC', 'DEPENDENT');

-- ----------------------------------------------------------------------------
-- 2. USERS & PROFILES
-- ----------------------------------------------------------------------------
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    role public.profile_role NOT NULL DEFAULT 'barista',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------------------
-- 3. INVENTORY & CATALOG
-- ----------------------------------------------------------------------------
CREATE TABLE public.item_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,

    CONSTRAINT uniq_category_name UNIQUE (name)
);


CREATE TABLE public.ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    brand TEXT,
    type TEXT,
    is_active BOOLEAN DEFAULT true NOT NULL,
    category TEXT NOT NULL
);

CREATE UNIQUE INDEX uniq_active_ingredient_name
ON public.ingredients (name)
WHERE is_active = true;

CREATE TABLE public.items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL CONSTRAINT chk_items_price_positive CHECK (price >= 0),
    category_id INTEGER REFERENCES public.item_categories(id) ON DELETE SET NULL,
    description TEXT,
    featured_rank SMALLINT DEFAULT 0 NOT NULL,
    is_available BOOLEAN DEFAULT true NOT NULL,
    image_url TEXT
);

CREATE UNIQUE INDEX uniq_active_item_per_category
ON public.items (category_id, name)
WHERE is_available = true;

CREATE TABLE public.item_variations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price INTEGER NOT NULL CONSTRAINT chk_item_variations_price_positive CHECK (price >= 0),
    is_available BOOLEAN DEFAULT true NOT NULL
);

CREATE UNIQUE INDEX uniq_item_variation_name
ON public.item_variations (item_id, LOWER(TRIM(name)))
WHERE is_available = true;

-- ----------------------------------------------------------------------------
-- 4. MENU CUSTOMIZATIONS (MODIFIERS)
-- ----------------------------------------------------------------------------
CREATE TABLE public.modifier_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    min_selections SMALLINT DEFAULT 0 NOT NULL,
    max_selections SMALLINT,

    CONSTRAINT uniq_modifier_group_name UNIQUE (name),
    CONSTRAINT chk_modifier_group_bounds CHECK (
        max_selections IS NULL OR max_selections >= min_selections
    )
);

CREATE TABLE public.modifier_group_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES public.modifier_groups(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES public.item_categories(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES public.items(id) ON DELETE CASCADE,

    CONSTRAINT chk_category_OR_item_logic CHECK (
        (category_id IS NOT NULL AND item_id IS NULL)
        OR
        (category_id IS NULL AND item_id IS NOT NULL)
    )
);
-- Prevent duplicates
CREATE UNIQUE INDEX uniq_mgr_item
ON public.modifier_group_rules(group_id, item_id)
WHERE item_id IS NOT NULL;

CREATE UNIQUE INDEX uniq_mgr_category
ON public.modifier_group_rules(group_id, category_id)
WHERE category_id IS NOT NULL;

CREATE TABLE public.modifiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES public.modifier_groups(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price_adjustment INTEGER DEFAULT 0 NOT NULL,
    ingredient_id INTEGER REFERENCES public.ingredients(id),
    quantity INTEGER DEFAULT 1 NOT NULL CONSTRAINT chk_modifiers_qty_positive CHECK (quantity > 0),
    behavior public.modifier_behavior DEFAULT 'STATIC' NOT NULL,
    is_available BOOLEAN DEFAULT true NOT NULL,
    dependency_source INTEGER NULL REFERENCES public.modifier_groups(id),

    CONSTRAINT chk_modifier_dependency_logic CHECK (
        (behavior = 'STATIC' AND dependency_source IS NULL)
        OR
        (behavior = 'DEPENDENT' AND dependency_source IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uniq_active_modifier_per_group
ON public.modifiers (group_id, LOWER(TRIM(name)))
WHERE is_available = true;

-- ----------------------------------------------------------------------------
-- 5. PURCHASING & RECIPES
-- ----------------------------------------------------------------------------
CREATE TABLE public.purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id INTEGER REFERENCES public.ingredients(id) ON DELETE RESTRICT,
    purchase_date DATE DEFAULT CURRENT_DATE NOT NULL,
    quantity INTEGER NOT NULL CONSTRAINT chk_purchases_qty_positive CHECK (quantity > 0),
    cost_total INTEGER NOT NULL CONSTRAINT chk_purchases_cost_positive CHECK (cost_total >= 0),
    supplier TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

CREATE TABLE public.recipes (
    item_variation_id INTEGER NOT NULL REFERENCES public.item_variations(id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL CONSTRAINT chk_recipes_amount_positive CHECK (amount > 0),
    PRIMARY KEY (item_variation_id, ingredient_id)
);

-- ----------------------------------------------------------------------------
-- 6. TRANSACTIONS (THE POS ENGINE)
-- ----------------------------------------------------------------------------
CREATE TABLE public.orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_order_id INTEGER REFERENCES public.orders(id) ON DELETE RESTRICT,
    customer_name TEXT,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    payment_method public.payment_type,
    shift public.shift_type DEFAULT 'day' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    price_total INTEGER DEFAULT 0 NOT NULL,
    cogs_total NUMERIC(12,2) DEFAULT 0 NOT NULL,
    kind public.order_kind DEFAULT 'sale' NOT NULL,

    CONSTRAINT chk_orders_kind_parent_logic CHECK (
        (kind = 'sale' AND parent_order_id IS NULL)
        OR
        (kind = 'refund' AND parent_order_id IS NOT NULL)
    ),

    CONSTRAINT chk_orders_signed_math CHECK (
        -- Sales must have zero or positive revenue
        (kind = 'sale' AND price_total >= 0)
        OR
        -- Refunds must have zero or negative revenue, and zero COGS
        (kind = 'refund' AND price_total <= 0 AND cogs_total <= 0)
    )
);

COMMENT ON COLUMN public.orders.payment_method IS 'NULL means unpaid order';

CREATE TABLE public.order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    original_order_item_id INTEGER REFERENCES public.order_items(id) NULL,
    item_variation_id INTEGER REFERENCES public.item_variations(id) ON DELETE SET NULL,

    -- The Dual-Status Matrix
    ledger_status public.ledger_state DEFAULT 'active' NOT NULL,
    fulfillment_status public.fulfillment_state DEFAULT 'preparing' NOT NULL,

    quantity INTEGER DEFAULT 1 NOT NULL,
    price_base INTEGER NOT NULL,
    cogs_base NUMERIC(10,2) DEFAULT 0 NOT NULL,
    price_total INTEGER DEFAULT 0 NOT NULL,
    cogs_total NUMERIC(12,2) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_order_items_base_positive CHECK (
        -- Base values are immutable truths, always positive
        price_base >= 0 AND cogs_base >= 0
    ),
    CONSTRAINT chk_order_items_signed_quantity CHECK (
        -- Normal items are positive quantities
        (ledger_status IN ('active', 'voided') AND quantity >= 0)
        OR
        -- Refunded clone items MUST be negative quantities, and capture zero COGS
        (ledger_status = 'refunded' AND quantity <= 0 AND cogs_total <= 0)
    ),
    CONSTRAINT chk_order_items_total_math CHECK (
        -- Enforce that the denormalized total is ALWAYS the mathematical product
        price_total = (price_base * quantity)
    )
);

CREATE TABLE public.order_item_modifiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id INTEGER NOT NULL REFERENCES public.order_items(id) ON DELETE CASCADE,
    modifier_id INTEGER NOT NULL REFERENCES public.modifiers(id),
    quantity_per_item INTEGER DEFAULT 1 NOT NULL,
    price_base INTEGER NOT NULL,
    cogs_base NUMERIC(10,2) DEFAULT 0 NOT NULL,
    resolved_ingredient_id INTEGER NULL REFERENCES public.ingredients(id) ON DELETE SET NULL,

    CONSTRAINT uniq_modifier_per_order_item UNIQUE (order_item_id, modifier_id),
    CONSTRAINT chk_oim_qty_not_zero CHECK (quantity_per_item != 0),
    CONSTRAINT chk_oim_cogs_positive CHECK (cogs_base >= 0),

    CONSTRAINT chk_oim_refund_logic CHECK (
        quantity_per_item != 0 AND
    )
);

-- ----------------------------------------------------------------------------
-- 7. PERFORMANCE INDEXES
-- ----------------------------------------------------------------------------
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at DESC);
CREATE INDEX idx_orders_parent_id ON public.orders USING btree (parent_order_id);
CREATE INDEX idx_orders_profile_id ON public.orders USING btree (profile_id);
CREATE INDEX idx_orders_unpaid ON public.orders USING btree (created_at) WHERE payment_method IS NULL;
CREATE INDEX idx_order_items_ledger ON public.order_items USING btree (ledger_status);
CREATE INDEX idx_order_items_fulfillment ON public.order_items USING btree (fulfillment_status);
CREATE INDEX idx_orders_kind_created_at ON public.orders USING btree (kind, created_at);

CREATE INDEX idx_mgr_item_id ON public.modifier_group_rules(item_id);
CREATE INDEX idx_mgr_category_id ON public.modifier_group_rules(category_id);

CREATE INDEX idx_item_variations_item_id ON public.item_variations USING btree (item_id);
CREATE INDEX idx_items_category_id ON public.items USING btree (category_id);
CREATE INDEX idx_recipes_variation_id ON public.recipes USING btree (item_variation_id);
CREATE INDEX idx_recipes_ingredient_id ON public.recipes USING btree (ingredient_id);
CREATE INDEX idx_purchases_ingredient_id ON public.purchases USING btree (ingredient_id);
CREATE INDEX idx_modifiers_ingredient_id ON public.modifiers USING btree (ingredient_id);

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);
CREATE INDEX idx_oim_order_item_id ON public.order_item_modifiers USING btree (order_item_id);
CREATE INDEX idx_oim_modifier_id ON public.order_item_modifiers USING btree (modifier_id);
CREATE INDEX idx_oim_resolved_ingredient_id ON public.order_item_modifiers (resolved_ingredient_id);

-- ----------------------------------------------------------------------------
-- 8. COSTING VIEWS (ANALYTICS)
-- ----------------------------------------------------------------------------

-- A standard view is fine here, as it's a very fast index scan to get the latest price.
CREATE VIEW public.view_ingredient_costs AS
    SELECT DISTINCT ON (ingredient_id)
        ingredient_id,
        purchase_date,
        (cost_total::numeric / NULLIF(quantity, 0)) AS cost_per_unit
    FROM public.purchases
    ORDER BY ingredient_id, purchase_date DESC, id DESC;

CREATE MATERIALIZED VIEW public.item_variation_cogs AS
    WITH resolved_rules AS (
        -- QUERY A: Rules applied directly to the item
        SELECT
            item_id AS target_item_id,
            group_id
        FROM public.modifier_group_rules
        WHERE item_id IS NOT NULL

        UNION -- (Automatically deduplicates accidental overlaps)

        -- QUERY B: Rules applied to the category, expanded to all items in that category
        SELECT
            i.id AS target_item_id,
            mgr.group_id
        FROM public.modifier_group_rules mgr
        JOIN public.items i ON mgr.category_id = i.category_id
        WHERE mgr.category_id IS NOT NULL
    ),
    base_costs AS (
        -- 1. Calculate the physical recipe cost per VARIATION
        SELECT
            iv.id AS variation_id,
            COALESCE(SUM(r.amount * vic.cost_per_unit), 0) AS base_cogs
        FROM public.item_variations iv
        LEFT JOIN public.recipes r ON iv.id = r.item_variation_id
        LEFT JOIN public.view_ingredient_costs vic ON r.ingredient_id = vic.ingredient_id
        GROUP BY iv.id
        ),
    mandatory_group_averages AS (
        -- 2. Calculate mandatory modifiers (like Sugar Level) per ITEM
        SELECT
            i.id AS item_id,
            mg.id AS group_id,
            COALESCE(AVG(m.quantity * vic.cost_per_unit), 0) AS avg_group_cogs,
            COALESCE(AVG(m.price_adjustment), 0) AS avg_group_price_adj
        FROM public.items i
        JOIN resolved_rules rr ON rr.target_item_id = i.id
        JOIN public.modifier_groups mg ON rr.group_id = mg.id
        JOIN public.modifiers m ON mg.id = m.group_id AND m.is_available = true
        LEFT JOIN public.view_ingredient_costs vic ON m.ingredient_id = vic.ingredient_id
        WHERE mg.min_selections >= 1 AND m.behavior = 'STATIC'
        GROUP BY i.id, mg.id
        ),
    modifier_costs AS (
        -- 3. Roll up modifier costs
        SELECT
            item_id,
            SUM(avg_group_cogs) AS total_avg_modifier_cogs,
            SUM(avg_group_price_adj) AS total_avg_modifier_price_adj
        FROM mandatory_group_averages
        GROUP BY item_id
        )

    -- 4. Bring it all together to show exact margins per variation
    SELECT
        iv.id AS variation_id,
        i.name AS item_name,
        iv.name AS variation_name,
        iv.price AS base_price,

        -- Selling Price Math
        (iv.price + COALESCE(mc.total_avg_modifier_price_adj, 0)) AS selling_price,

        -- COGS Math
        bc.base_cogs,
        COALESCE(mc.total_avg_modifier_cogs, 0) AS modifier_cogs,
        (bc.base_cogs + COALESCE(mc.total_avg_modifier_cogs, 0)) AS total_cogs,

        -- Profit Math
        ((iv.price + COALESCE(mc.total_avg_modifier_price_adj, 0)) -
        (bc.base_cogs + COALESCE(mc.total_avg_modifier_cogs, 0))) AS gross_profit,

        -- Margin %
        CASE
            WHEN (iv.price + COALESCE(mc.total_avg_modifier_price_adj, 0)) = 0 THEN 0::numeric
            ELSE ROUND(
                (((iv.price + COALESCE(mc.total_avg_modifier_price_adj, 0)) - (bc.base_cogs + COALESCE(mc.total_avg_modifier_cogs, 0))) /
                NULLIF((iv.price + COALESCE(mc.total_avg_modifier_price_adj, 0)), 0)::numeric) * 100,
                1
            )
        END AS margin_percent

    FROM public.item_variations iv
    JOIN public.items i ON iv.item_id = i.id
    LEFT JOIN base_costs bc ON iv.id = bc.variation_id
    LEFT JOIN modifier_costs mc ON i.id = mc.item_id;

CREATE UNIQUE INDEX idx_item_variation_cogs_id ON public.item_variation_cogs (variation_id);

-- ----------------------------------------------------------------------------
-- 9. TRIGGERS (refresh function)
-- ----------------------------------------------------------------------------

CREATE FUNCTION refresh_item_variation_cogs()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER set search_path = public, pg_temp -- Allows the function to bypass row-level security for the refresh
AS $$
BEGIN
  -- CONCURRENTLY allows the view to be read while it's updating.
  -- Note: CONCURRENTLY requires a UNIQUE index on the materialized view (which you already added!)
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.item_variation_cogs;
END;
$$;

-- Enable the pg_cron extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Schedule the refresh for 18:00 UTC (02:00 AM local time) every day
SELECT cron.schedule(
  'nightly-cogs-refresh', -- A unique name for your job
  '0 18 * * *',           -- The cron schedule expression
  $$SELECT public.refresh_item_variation_cogs();$$
);

-- To unschedule uncomment the following line
-- SELECT cron.unschedule('nightly-cogs-refresh');

-- ----------------------------------------------------------------------------
-- 10. TRIGGERS (adding users with auth function)
-- ----------------------------------------------------------------------------

-- 1. Create the function that will execute when a user is created
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER set search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, role)
  VALUES (
    new.id,
    -- We extract username and role from the metadata JSON we will pass in SvelteKit
    -- new.raw_user_meta_data->>'username',
    COALESCE(
          new.raw_user_meta_data->>'username',
          'user_' || substr(new.id::text, 1, 8)
        ),
    COALESCE(
      (new.raw_user_meta_data->>'role')::public.profile_role,
      'barista'
    )
  );
  RETURN new;
END;
$$;

-- 2. Bind the function to a trigger on the auth.users table
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 11. TRIGGERS (freezing settled ticket functions)
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION protect_settled_orders()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.payment_method IS NOT NULL THEN
        RAISE EXCEPTION 'Audit Violation: Cannot modify financial data on a settled order.';
    END IF;
    RETURN NEW;
END;
$$;

-- This allows baristas to update customer_name or profile_id (loyalty points) AFTER payment!
CREATE TRIGGER trigger_protect_settled_orders
BEFORE UPDATE ON public.orders
FOR EACH ROW
WHEN (
    OLD.payment_method IS NOT NULL AND
    (
        OLD.price_total IS DISTINCT FROM NEW.price_total OR
        OLD.cogs_total IS DISTINCT FROM NEW.cogs_total OR
        OLD.payment_method IS DISTINCT FROM NEW.payment_method OR
        OLD.kind IS DISTINCT FROM NEW.kind OR
        OLD.shift IS DISTINCT FROM NEW.shift
    )
)
EXECUTE FUNCTION protect_settled_orders();

CREATE OR REPLACE FUNCTION protect_settled_order_items()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER set search_path = public
AS $$
DECLARE
    ticket_payment_method text;
    target_order_id int;
BEGIN
    -- Handle both UPDATE (NEW/OLD) and DELETE (OLD)
    target_order_id := COALESCE(OLD.order_id, NEW.order_id);

    IF target_order_id IS NULL THEN
        RAISE EXCEPTION 'Audit Violation: Order reference is missing.';
    END IF;

    -- Look up the parent order's payment method
    SELECT payment_method INTO ticket_payment_method
    FROM public.orders WHERE id = target_order_id;

    -- If the ticket is paid, reject the transaction violently!
    IF ticket_payment_method IS NOT NULL THEN
        RAISE EXCEPTION 'Audit Violation: Cannot alter or delete items on a settled ticket. Issue a refund instead.';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

-- Trigger 1: The restrictive UPDATE (allows fulfillment status changes, blocks tampering)
CREATE TRIGGER trigger_protect_settled_order_items_update
BEFORE UPDATE ON public.order_items
FOR EACH ROW
WHEN (
    OLD.price_base IS DISTINCT FROM NEW.price_base OR
    OLD.price_total IS DISTINCT FROM NEW.price_total OR
    OLD.cogs_base IS DISTINCT FROM NEW.cogs_base OR
    OLD.cogs_total IS DISTINCT FROM NEW.cogs_total OR
    OLD.quantity IS DISTINCT FROM NEW.quantity OR
    OLD.item_variation_id IS DISTINCT FROM NEW.item_variation_id OR
    OLD.order_id IS DISTINCT FROM NEW.order_id OR
    OLD.ledger_status IS DISTINCT FROM NEW.ledger_status
)
EXECUTE FUNCTION protect_settled_order_items();

-- Trigger 2: The DELETE (fires every time someone tries to delete a row)
CREATE TRIGGER trigger_protect_settled_order_items_delete
BEFORE DELETE ON public.order_items
FOR EACH ROW
EXECUTE FUNCTION protect_settled_order_items();

-- Trigger 3: The INSERT (blocks adding new items to a settled ticket)
CREATE TRIGGER trigger_protect_settled_order_items_insert
BEFORE INSERT ON public.order_items
FOR EACH ROW
EXECUTE FUNCTION protect_settled_order_items(); -- THE FIX: Corrected function name

CREATE OR REPLACE FUNCTION protect_settled_order_item_modifiers()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    ticket_payment_method text;
    target_order_item_id int;
BEGIN
    -- 1. Explicit handling per operation
    IF TG_OP = 'DELETE' THEN
        target_order_item_id := OLD.order_item_id;
    ELSIF TG_OP = 'UPDATE' THEN
        -- THE FIX: Hard-block moving modifiers to different items
        IF OLD.order_item_id IS DISTINCT FROM NEW.order_item_id THEN
            RAISE EXCEPTION 'Audit Violation: Modifiers cannot be transferred between order items.';
        END IF;
        target_order_item_id := NEW.order_item_id;
    ELSE
        -- INSERT
        target_order_item_id := NEW.order_item_id;
    END IF;

    -- 2. Fetch payment method (Using JOIN is slightly more performant than a sub-select)
    SELECT o.payment_method
    INTO ticket_payment_method
    FROM public.orders o
    JOIN public.order_items oi ON o.id = oi.order_id
    WHERE oi.id = target_order_item_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Audit Violation: Parent order not found for modifier.';
    END IF;

    -- 3. Block if settled
    IF ticket_payment_method IS NOT NULL THEN
        RAISE EXCEPTION 'Audit Violation: Cannot modify modifiers on a settled ticket. Issue a refund instead.';
    END IF;

    -- 4. Return correct record state
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

-- INSERT
CREATE TRIGGER trigger_protect_settled_order_item_modifiers_insert
BEFORE INSERT ON public.order_item_modifiers
FOR EACH ROW
EXECUTE FUNCTION protect_settled_order_item_modifiers();

-- UPDATE (strict)
CREATE TRIGGER trigger_protect_settled_order_item_modifiers_update
BEFORE UPDATE ON public.order_item_modifiers
FOR EACH ROW
EXECUTE FUNCTION protect_settled_order_item_modifiers();

-- DELETE
CREATE TRIGGER trigger_protect_settled_order_item_modifiers_delete
BEFORE DELETE ON public.order_item_modifiers
FOR EACH ROW
EXECUTE FUNCTION protect_settled_order_item_modifiers();




-- 1. Secure the Standard View
ALTER VIEW public.view_ingredient_costs SET (security_invoker = true);

-- 2. Secure the Materialized View (The Hard Lockdown)
REVOKE ALL ON public.item_variation_cogs FROM PUBLIC, anon, authenticated; -- revoke all access from public API roles
GRANT SELECT ON public.item_variation_cogs TO service_role; -- grant access ONLY to the specific database roles that need it.

-- Revoke access from the frontend clients
-- 3. Secure the Function to refresh the Materialized View
REVOKE EXECUTE ON FUNCTION public.refresh_item_variation_cogs() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_item_variation_cogs() TO service_role;

-- 4. Lock down all tables by enabling Row Level Security
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifier_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifier_group_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STORAGE RLS POLICIES FOR 'menu_images' BUCKET
-- ============================================================================

-- 1. READ ACCESS: Anyone can view the images
-- Even though the bucket is public, it's good practice to have a read policy.
CREATE POLICY "Public Menu Images Viewable"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'menu_images');

-- 2. INSERT ACCESS: Only managers can upload new images
CREATE POLICY "Managers can upload menu images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'menu_images' AND
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role = 'manager'
    )
);

-- 3. UPDATE ACCESS: Only managers can update existing images
CREATE POLICY "Managers can update menu images"
ON storage.objects FOR UPDATE
TO authenticated
USING (
    bucket_id = 'menu_images' AND
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role = 'manager'
    )
);

-- 4. DELETE ACCESS: Only managers can delete images
CREATE POLICY "Managers can delete menu images"
ON storage.objects FOR DELETE
TO authenticated
USING (
    bucket_id = 'menu_images' AND
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role = 'manager'
    )
);
